language: go
go:
- 1.12.x
env:
  matrix:
  - GO111MODULE=on GOLINT_VERSION=v1.16.0
  global:
    secure: X4vIEhRkqMpuS6fMkjrkP7Pom5Pgf1x3TmueoP9cRqUhaXJtit4hSsjukv8eqUxtWLYa0cKyDNpCvwIvViysPbjwxyAa38+4jdRapRzlIEikoY7cEgEZokvNMAukJqlW2AXLHj4H4eVjYSFdwrIkmLITNAifK+neIknGRvcxa9slTlSk+rNVIuexQckvbWd1nmHiGimHHhdCLWmqGRpbaYgoHSue+XKmDYhNz+HeTC0q3fKp1COeTDJadxX4LeY2NLp8J/NrFPbmwabzVP/xfuMEW4TeSFISGJZnTraX1Qor5bTylUU98eHnu0Wstiq1u64e0B8206QlgQraruMY/dNR4XoncrC5BISZKjeSAYg4Yj2L9hnbtxOEGHosau/7YYxsms5ERpSSKZpu6D9eSuXZvZoawQCKDd2bkhtMJQgccMZxiGddNzmM8enZUTuEJuoGSG5aLJyptDCrnZlOP+OXYH2Lsvgu/zSC4mSUsl1d+4naz+ixZ+KZXGSEaAeNLNO2RV0SfqEgtTTnYjKjT48rwUMbxzbFuB6CrC2L9nAvxCFCokteuhbW8p+G+vyuVlTNk/NSJkd4a2/6YhzHecSuXfrGnyEAYJzBVo7iGnTtnwYHz/0ocvzE+uVabhXk0J47o+aVE/Yd5LT6G8WPnMlBPbPbgd874p6izYEvfrg=
before_script:
- go vet -printf ./...
install:
- go get github.com/mattn/goveralls
- curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh |
  sh -s -- -b $(go env GOPATH)/bin ${GOLINT_VERSION}
- go mod download
