language: go

go:
  - "1.12.x"

env:
  - GO111MODULE=on
  - GOLINT_VERSION=v.1.16.0

before_script:
  - go vet -printf ./...

install:
  # Add Godeps dependencies to GOPATH and PATH
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin ${GOLINT_VERSION}
  - go mod download